from typing import List, Dict
from .models import Task

def generate_plan_for_task(task: Task) -> List[Dict]:
    """
    Placeholder for Claude-based plan generation.
    Returns a trivial plan with one step.
    """
    return [{"step": 1, "description": f"Plan for {task.goal} needs to be generated by the planner"}]
